name: ustahub
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.7.2

dependencies:
  app_settings: ^6.1.1
  dio: ^5.9.0
  dotted_line: ^3.2.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  get: ^4.7.2
  google_fonts: ^6.3.2
  http: ^1.6.0
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  intl: 
  flutter_localizations: 
    sdk: flutter
  dots_indicator: ^4.0.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  custom_rating_bar: ^3.0.0
  readmore: ^3.0.0
  table_calendar: ^3.2.0
  intl_phone_number_input: ^0.7.5
  image_picker: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  turkmen_localization_support: ^0.0.13
  fluttertoast: ^9.0.0
  country_picker: ^2.0.27
  dotted_border: ^3.1.0
  maps_launcher: ^3.0.0+1
  shimmer: ^3.0.0
  collection: ^1.19.1
  timelines_upgraded: ^0.1.1
  shimmer_ai: ^1.3.0
  zego_zim: ^2.23.0
  zego_zimkit: ^1.19.6
  zego_express_engine: ^3.22.1
  fluentui_system_icons: ^1.1.226
  zego_zpns: ^2.8.0
  # flutter_local_notifications: ^19.5.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.7
  firebase_notifications_handler: ^2.0.2+1
  url_launcher: ^6.3.2
  supabase_flutter: ^2.0.0
  # ZegoCloud dependencies - uncomment when ready to integrate
  # zego_uikit_prebuilt_call: ^4.20.5
  # zego_uikit: ^2.28.5
  # sqflite: ^2.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# dependency_overrides:
#   file_picker: ^8.1.6

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - imgs/
    - images/Logo/
